### ISSUE TITLE
game shows no ui, process keeps running

### ISSUE THREAD

**Issue by wowselim** [Hugobros3/chunkstories#16]
I wanted to have a look at the binary on the website but after I hit the play button, no ui shows up but the process keeps running.

I get the following exception:
`
```
ERROR:Exception in thread "Main OpenGL Rendering thread" java.lang.NullPointerException
ERROR:  at org.lwjgl.system.Checks.check(Checks.java:94)
ERROR:  at org.lwjgl.glfw.GLFW.nglfwSetKeyCallback(GLFW.java:2819)
ERROR:  at org.lwjgl.glfw.GLFW.glfwSetKeyCallback(GLFW.java:2848)
ERROR:  at io.xol.chunkstories.input.lwjgl3.Lwjgl3ClientInputsManager.<init>(Lwjgl3ClientInputsManager.java:101)
ERROR:  at io.xol.engine.base.GameWindowOpenGL_LWJGL3.stage_2_init(GameWindowOpenGL_LWJGL3.java:348)
ERROR:  at io.xol.chunkstories.client.Client.<init>(Client.java:183)
ERROR:  at io.xol.chunkstories.client.Client.main(Client.java:127)
```

**Comment by Hugobros3** [comment]
Don't bother with those binaries, they are hilariously outdated. I will remove them from the site & add a note to make a fresh build instead, since I don't want to release a half-baked rewrite either.
